name: "Hugi Upload Job"
on:
  push
  # schedule:
  #   # every day 12:30 and 21:30 UCT
  #   - cron: "0 12,21 * * *"

jobs:
  generate_content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn run-job
