name: "Hugi Upload Job"
on:
  workflow_dispatch:
  schedule:
    # every day 12:30 and 21:30 UCT
    - cron: "0 12,21 * * *"

jobs:
  generate_content:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn run-job
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_ACCOUNT_EMAIL: ${{ secrets.SUPABASE_ACCOUNT_EMAIL }}
          SUPABASE_ACCOUNT_PASSWORD: ${{ secrets.SUPABASE_ACCOUNT_PASSWORD }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
